/**
 * Interface strings for /admin. The admin is an internal tool for the four super admins, so it
 * is English-only by design; public copy stays bilingual under src/content.
 */
export const ADMIN = {
  brand: "dewee admin",
  nav: {
    dashboard: "Dashboard",
    pages: "Pages",
    posts: "Posts",
    keys: "API keys",
    leads: "Leads",
    audit: "Audit log",
    site: "View site",
    developers: "Developer docs",
    signOut: "Sign out",
    signedInAs: "Signed in as",
  },
  login: {
    title: "Sign in",
    lede: "The admin is limited to the dewee super admins.",
    email: "Work email",
    sendCode: "Email me a code",
    code: "6-digit code",
    codeHint: "The code expires in 10 minutes. You have 5 attempts.",
    verify: "Sign in",
    sent: "If this address can sign in, a code is on its way. Check your inbox.",
    devLog: "Local development: the code is printed in the dev server console.",
    invalid: "That code is not valid. Check it or request a new one.",
    rateLimited: "Too many attempts. Wait a few minutes and try again.",
    unavailable: "Email sign-in is not available on this deployment.",
    useAccess: "Sign in through Cloudflare Access",
    accessHint: "Your Cloudflare Access identity signs you in automatically when it is one of the super admins.",
    otherEmail: "Use a different email",
  },
  dashboard: {
    title: "Dashboard",
    lede: "Content, credentials and leads at a glance.",
    published: "published",
    drafts: "drafts",
    archived: "archived",
    leads30: "leads in the last 30 days",
    activeKeys: "active API keys",
    recent: "Recent activity",
    quick: "Quick actions",
    newPage: "New page",
    newPost: "New post",
    newKey: "Create an API key",
  },
  list: {
    search: "Search title or slug",
    status: "Status",
    locale: "Language",
    any: "Any",
    filter: "Filter",
    empty: "Nothing matches these filters.",
    title: "Title",
    slug: "Slug",
    updated: "Updated",
    version: "Ver.",
    newer: "Previous",
    older: "Next",
    showing: "Showing",
    of: "of",
  },
  editor: {
    newTitle: "New",
    back: "Back to the list",
    fields: "Details",
    title: "Title",
    slug: "Slug",
    slugHint: "Lowercase letters, digits and dashes. Leave empty to derive it from the title.",
    locale: "Language",
    description: "Description",
    layout: "Layout",
    translationKey: "Translation key",
    translationHint: "The same key links the English and Vietnamese versions.",
    tags: "Tags",
    tagsHint: "Comma separated, up to 10.",
    author: "Author",
    authorHint: "A founder id (duy, cuong, viet) links to their profile. Empty means the dewee team.",
    cover: "Cover image URL",
    seo: "Search and sharing",
    seoTitle: "SEO title",
    seoDescription: "SEO description",
    ogImage: "Social image URL",
    noindex: "Hide from search engines",
    blocks: "Blocks (JSON)",
    blocksHint: "An array of { type, props, section? }. Errors are checked against the block schemas as you type.",
    body: "Body (Markdown)",
    bodyHint: "Raw HTML is escaped. Headings get anchors automatically.",
    note: "Revision note",
    save: "Save",
    saving: "Saving…",
    saved: "Saved as version",
    create: "Create draft",
    publish: "Publish",
    unpublish: "Unpublish",
    archive: "Archive",
    delete: "Delete",
    confirmDelete: "Delete this permanently? Revisions are deleted too.",
    preview: "Refresh preview",
    openPreview: "Open preview in a new tab",
    viewLive: "View live",
    validJson: "Blocks are valid.",
    badJson: "Blocks are not valid JSON",
    conflict: "Someone saved a newer version. Reload to see it, then reapply your change.",
    catalog: "Block catalog",
    insert: "Insert example",
    schema: "Schema",
    revisions: "Revisions",
    restore: "Restore",
    confirmRestore: "Restore this revision as a new version?",
    noRevisions: "No revisions yet.",
    status: "Status",
    version: "Version",
    shortcut: "Ctrl/⌘ + S saves.",
    previewTitle: "Live preview",
  },
  keys: {
    title: "API keys",
    lede: "Keys authenticate the REST API, the CLI and the MCP server. A key is shown once, when it is created.",
    name: "Name",
    nameHint: "What uses this key, for example “Claude Desktop on Duy's laptop”.",
    scopes: "Scopes",
    expires: "Expires",
    never: "Never",
    days: "days",
    create: "Create key",
    created: "Copy this key now. It will not be shown again.",
    copy: "Copy",
    prefix: "Prefix",
    owner: "Owner",
    lastUsed: "Last used",
    revoke: "Revoke",
    revoked: "Revoked",
    expired: "Expired",
    active: "Active",
    confirmRevoke: "Revoke this key? Anything using it stops working immediately.",
    none: "No API keys yet.",
    badName: "Give the key a name (up to 80 characters).",
    badScopes: "Choose at least one scope.",
  },
  leads: {
    title: "Leads",
    lede: "Submissions from the contact and partner forms, newest first.",
    kind: "Kind",
    search: "Search email, name or company",
    when: "Received",
    who: "Contact",
    details: "Details",
    empty: "No leads match.",
  },
  audit: {
    title: "Audit log",
    lede: "Every write through the admin, the API, the CLI and MCP, newest first.",
    when: "When",
    actor: "Actor",
    action: "Action",
    target: "Target",
    detail: "Detail",
    older: "Older entries",
    empty: "No activity yet.",
  },
  preview: {
    banner: "Preview",
    draft: "This is how the page will look. It is not public until published.",
    invalid: "The preview could not be rendered:",
  },
  errors: {
    csrf: "Your session form expired. Reload the page and try again.",
    generic: "Something went wrong. Try again.",
  },
} as const;
