/// <reference types="node" />
/**
 * Regenerates migrations/0010_seed_releases.sql: a sanitised snapshot of the dewee GitHub releases
 * so /changelog has content before the hourly sync (which needs a GITHUB_TOKEN secret) first runs.
 *
 *   pnpm changelog:snapshot                          # gh api, repo from CHANGELOG_REPO or nextlevelbuilder/dewee
 *   pnpm changelog:snapshot -- --input releases.json # a saved `gh api .../releases` array instead
 *
 * Requires an authenticated `gh` CLI with read access to the private repository. The output is
 * committed to a public repository, so every body goes through the same sanitiser as the sync,
 * and no github.com URL is stored. Review the diff before committing.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { sanitiseReleaseName, sanitiseReleaseNotes } from "../src/lib/server/seo/changelog/release-notes-sanitiser.ts";
import { channelOf, compareTags, parseTag } from "../src/lib/server/seo/changelog/release-groups.ts";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = resolve(ROOT, "migrations/0010_seed_releases.sql");

type Release = { tag_name: string; name: string | null; prerelease: boolean; draft: boolean; published_at: string | null; body: string | null };

function arg(name: string): string | undefined {
  const i = process.argv.indexOf(`--${name}`);
  return i > 0 ? process.argv[i + 1] : undefined;
}

function isRelease(v: unknown): v is Release {
  const r = v as Record<string, unknown> | null;
  return !!r && typeof r.tag_name === "string" && typeof r.prerelease === "boolean" && typeof r.draft === "boolean";
}

function fetchWithGh(repo: string): unknown[] {
  // One compact JSON object per line keeps parsing independent of how gh joins paginated arrays.
  const out = execFileSync(
    "gh",
    ["api", `repos/${repo}/releases?per_page=100`, "--paginate", "--jq", ".[] | {tag_name, name, prerelease, draft, published_at, body}"],
    { encoding: "utf8", maxBuffer: 256 * 1024 * 1024 },
  );
  return out.split("\n").filter((l) => l.trim()).map((l) => JSON.parse(l) as unknown);
}

/** SQL string literal; control characters other than tab and newline are dropped. */
function sql(value: string | null): string {
  if (value === null) return "NULL";
  return `'${value.replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/g, "").replace(/'/g, "''")}'`;
}

function main(): void {
  const repo = arg("repo") ?? process.env.CHANGELOG_REPO ?? "nextlevelbuilder/dewee";
  if (!/^[\w.-]+\/[\w.-]+$/.test(repo)) throw new Error(`Invalid repo "${repo}", expected owner/name`);
  const input = arg("input");
  const raw: unknown[] = input ? (JSON.parse(readFileSync(resolve(input), "utf8")) as unknown[]) : fetchWithGh(repo);
  if (!Array.isArray(raw)) throw new Error("Expected a JSON array of releases");

  const releases = raw
    .filter(isRelease)
    .filter((r) => !r.draft && r.published_at && !Number.isNaN(Date.parse(r.published_at)) && parseTag(r.tag_name))
    .sort((a, b) => compareTags(b.tag_name, a.tag_name));
  if (!releases.length) throw new Error("No published releases found; refusing to write an empty seed");

  const generatedAt = new Date().toISOString();
  const rows = releases.map((r) => {
    const values = [
      sql(r.tag_name),
      sql(sanitiseReleaseName(r.name, r.tag_name, repo)),
      sql(channelOf(r.tag_name, r.prerelease)),
      sql(r.published_at),
      sql(sanitiseReleaseNotes(r.body, { repo, tag: r.tag_name })),
      "NULL",
      sql(generatedAt),
    ].join(", ");
    return `INSERT INTO releases (tag, name, channel, published_at, body, url, synced_at) VALUES (${values})
  ON CONFLICT(tag) DO UPDATE SET name = excluded.name, channel = excluded.channel, published_at = excluded.published_at, body = excluded.body, url = NULL, synced_at = excluded.synced_at;`;
  });

  const stable = releases.filter((r) => channelOf(r.tag_name, r.prerelease) === "stable").length;
  const header = [
    "-- Sanitised snapshot of the dewee GitHub releases for /changelog.",
    `-- ${releases.length} releases (${stable} stable, ${releases.length - stable} beta), newest ${releases[0].tag_name}.`,
    "-- Generated by scripts/snapshot-releases.ts; do not edit by hand. The hourly sync keeps it current.",
    "-- Release pages of the private repository are never linked, so url stays NULL.",
    "UPDATE releases SET url = NULL WHERE url IS NOT NULL;",
    "",
  ];
  writeFileSync(OUT, `${header.join("\n")}${rows.join("\n")}\n`);
  console.log(`wrote ${OUT} (${releases.length} releases, ${stable} stable)`);
}

main();
